### ISSUE TITLE
Running against a Raw URL throws Parsing errors

### ISSUE THREAD

**Issue by salameer** [Azure/openapi-validation-tools#36]
Ran the command:
node validate.js spec "https://github.com/Azure/openapi-validation-tools/blob/master/arm-mediaservices/2015-10-01/swagger/media.json" --json

And got the following error, there seems to be an issue with fetching the json or I'm running it wrong If so let's make more idiomatic for AWESOME people like me: 

C:\Users\sameal\workspace\openapi-validation-tools-master>node validate.js example https://github.com/Azure/openapi-validation-tools/blob/master/arm-mediaservices/2015-10-01/swagger/media.json --json

> Validating "examples" and "x-ms-examples" in https://github.com/Azure/openapi-validation-tools/blob/master/arm-mediaservices/2015-10-01/swagger/media.json:

PARSE_SPEC_ERROR - Error occurred in parsing the spec "https://github.com/Azure/openapi-validation-tools/blob/master/arm-mediaservices/2015-10-01/swagger/media.json".  Error parsing https://github.com/Azure/openapi-validation-tools/blob/master/arm-mediaservices/2015-10-01/swagger/media.json
end of the stream or a document separator is expected at line 7, column 19:
      <head prefix="og: http://ogp.me/ns# fb: http://o ...
                      ^.

**Comment by amarzavery** [comment]
It should be a raw github url. That will give us the JSON, otherwise it would give you the html page.

Click on the raw button. That will reload the page. Then copy the url from the browser and use it as an input to the tool

![image](https://cloud.githubusercontent.com/assets/4521223/20464782/eb155ff6-af02-11e6-8bd1-6c61764d5956.png)

**Comment by salameer** [comment]
snaaaaaap, Got it! Thanks MS Superman

**Comment by amarzavery** [comment]
https://github.com/Azure/openapi-validation-tools/pull/41

**Comment by amarzavery** [comment]
We will auto convert it to a raw github url and let the user know about it.

**Comment by salameer** [comment]
That sounds like an awesome plan :)
