### ISSUE TITLE
Adding a "Verbose" flag to provide the detailed information on the response object

### ISSUE THREAD

**Issue by salameer** [Azure/openapi-validation-tools#40]
I'm suggesting that we add  a debug or verbose flag to running the tool to display the detailed errors summary

**Comment by amarzavery** [comment]
This is already supported. Please use the --json flag to get the detailed json object.

**Comment by amarzavery** [comment]
Updated the help.

Amars-MacBook-Pro:openapi-validation-tools amarz$ node validate.js 

Usage: node validate.js <command> <spec-path> [--json]

Commands:

  - spec <raw-github-url OR local file-path to the swagger spec> [--json]    | Description: Performs semantic validation of the spec.

  - example <raw-github-url OR local file-path to the swagger spec> [--json] | Description: Performs validation of x-ms-examples and examples present in the spec.

Options:
  --json - Provides the json object with detailed status report.

Amars-MacBook-Pro:openapi-validation-tools amarz$

**Comment by amarzavery** [comment]
#41
