### ISSUE TITLE
Integrate this tools into rest-api-specs

### ISSUE THREAD

**Issue by salameer** [Azure/openapi-validation-tools#50]
Reason it's not there right now:
- there are lots of existing violations
- we have warnings coming up in our tools that should not be blocking the CI.

What do we need to do:
- Differentiate blocking acceptable warnings VS blocking warnings.
-  come up with a plan for existing violations

Run the spec validator on all swagger currently in Master and  see what type of issues we find. if they are low hanging fruits then we can tackle them, if not we'll need to reach-out to the owners.

A suggestion here is to include Linter and this validation tool activation on latest rest-api-sec  preview -> Master migration proposal. we would not block on the Specs in Preview but there shouldn't be any errors reported from these tools with anything that's in Master

**Comment by vishrutshah** [comment]
Already completed
