### ISSUE TITLE
Query parameter fails validation as it's being encoded for validation, review logic and advise on expectations

### ISSUE THREAD

**Issue by veronicagg** [Azure/openapi-validation-tools#80]
Please review the logic on url enconding for model validation, please see https://travis-ci.com/Azure/azure-rest-api-specs-pr/jobs/70678014#L1412
"The parameter is a date-time in the query part of the url, so from a rest perspective it should be url-encoded, but from an SDK perspective it will just be a DateTime that the autorest SDK should url-encode before calling service.  I think this means we should not put x-ms-skip-url-encoding in swagger (since we want autorest to url-encode), and I tried putting url-encoded parameter format in example file but validator url-encoded that again (I turned : into %3A and ended up with %25%3A in the validation error message) which seems backwards.  Let me know if I’m misinterpreting the guidance or behavior, otherwise I think it’s a tooling bug that isn’t blocking us (our SDK works, and the way we’re validating our service and SDK behavior with examples is also working)."

**Comment by amarzavery** [comment]
closing the issue as this is resolved
